-- CreateTable
CREATE TABLE "TCEP_LOG_LOCALIDADE" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "LOC_NU" TEXT NOT NULL DEFAULT '1',
    "UFE_SG" TEXT NOT NULL DEFAULT '2',
    "LOC_NO" TEXT NOT NULL DEFAULT '3',
    "CEP" TEXT NOT NULL DEFAULT '4',
    "LOC_IN_SIT" TEXT NOT NULL DEFAULT '5',
    "LOC_IN_TIPO_LOC" TEXT NOT NULL DEFAULT '6',
    "LOC_NU_SUB" TEXT NOT NULL DEFAULT '7',
    "LOC_NO_ABREV" TEXT NOT NULL DEFAULT '8',
    "MUN_NU" TEXT NOT NULL DEFAULT '9'
);
